Test 55

diff --git a/.github/workflows/environment_deployment.yaml b/.github/workflows/environment_deployment.yaml
--- a/.github/workflows/environment_deployment.yaml
+++ b/.github/workflows/environment_deployment.yaml
@@ -9,21 +9,20 @@ on:
 
 jobs:
 
-  deploy_environment:
+  identify_environment:
     runs-on: ubuntu-latest
     env:
       GITHUB_TOKEN: ${{ github.token }}
+    outputs:
+      environment: ${{ steps.get_environment.outputs.environment }}
+      release_tag: ${{ steps.get_tags.outputs.release_tag }}
+      code_tag: ${{ steps.get_tags.outputs.code_tag }}
+      config_tag: ${{ steps.get_tags.outputs.config_tag }}
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
           ssh-key: "${{ secrets.COMMIT_KEY }}"
-      - name: Git config
-        run: |
-          git config --global user.email "infra-pipeline@dh.com"
-          git config --global user.name "Infrastructure Pipeline"
-          #      - run: |
-          #git fetch --prune --tags origin
       - name: Get relevant tags
         id: get_tags
         run: |
@@ -51,9 +50,41 @@ jobs:
           ENVIRONMENT=${ENVIRONMENT%-start}
           ENVIRONMENT=${ENVIRONMENT#refs/tags/release-[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*-}
           echo ${ENVIRONMENT}
+          if [[ -z "${ENVIRONMENT}" ]]; then
+            echo "Cannot identify environment - check *-environment-start tag - Exiting"
+            exit 1
+          fi
           echo "::set-output name=environment::${ENVIRONMENT}"
 
 
+  deploy_environment:
+    runs-on: ubuntu-latest
+    needs: identify_environment
+    env:
+      GITHUB_TOKEN: ${{ github.token }}
+      DEPLOYMENT_ENVIRONMENT: ${{ needs.identify_environment.outputs.environment }}
+      RELEASE_VERSION: ${{ needs.identify_environment.outputs.release_tag }}
+      CODE_TAG: ${{ needs.identify_environment.outputs.code_tag }}
+      CONFIG_TAG: ${{ needs.identify_environment.outputs.config_tag }}
+    environment: ${{ needs.identify_environment.outputs.environment }}
+    concurrency: ${{ needs.identify_environment.outputs.environment }}
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+          ssh-key: "${{ secrets.COMMIT_KEY }}"
+      - name: Git config
+        run: |
+          git config --global user.email "infra-pipeline@dh.com"
+          git config --global user.name "Infrastructure Pipeline"
+          #      - run: |
+          #git fetch --prune --tags origin
+      - name: Debug
+        run: |
+          echo "Environment: ${DEPLOYMENT_ENVIRONMENT}"
+          echo "Release version: ${RELEASE_VERSION}"
+          echo "Code tag: ${CODE_TAG}"
+          echo "Config tag: ${CONFIG_TAG}"
 
         #1. Process tag - get environment
         #2. Scan promotion.yaml - filter environment - get priorities
